services:
  web:
    build: .
    image: django_i
    container_name: django_c
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/ # use host bind volume (path is specified) to sync the project code on the container if we modify from the host machine
    ports:
      - 9000:8000
    env_file:
      - ./env/.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_c
    environment:
      POSTGRES_DB: mydatabase_dev
      POSTGRES_USER: ardian
      POSTGRES_PASSWORD: btre_db_password
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data # using docker-managed volume (name is specified instead of path)

volumes:
  db_data: