services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ardianumam/django-btre
    container_name: django_c
    command: gunicorn btre.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - db
    networks:
      - django_network

  db:
    image: postgres:alpine
    container_name: postgres_c
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./env/.env.prod.db
    networks:
      - django_network

  nginx:
    build: ./nginx
    image: ardianumam/nginx
    container_name: nginx_c
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 9000:80
    depends_on:
      - web
    networks:
      - django_network

volumes:
  db_data:
    name: django-realter-app_db_data
  static_volume:
    name: django-realter-app_static_volume
  media_volume:
    name: django-realter-app_media_volume

networks:
  django_network:
    name: django-realter-app_network