# Generated by Django 4.2.5 on 2024-11-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="photo_5",
            field=models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
        ),
    ]
